// <auto-generated />
using MediatorApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediatorApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201117002001_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("MediatorApi.Domain.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            Name = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            Name = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            Name = "Book 3"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            Name = "Book 4"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            Name = "Book 5"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            Name = "Book 6"
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            Name = "Book 7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
